name: "Setup Continuous Integration"
description: "Cache Dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Cache PNPM Dependencies
      uses: actions/cache@v3
      id: cache-primes
      with:
        path: ./client/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./client/pnpm-lock.yaml') }}

    - name: Install Dependencies
      run: cd client && pnpm
      shell: bash
