name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  NODE_VERSION: 21.x

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Continuous integration
        uses: ./.github/actions/ci-setup

      - name: Lint Application
        run: cd client && pnpm lint

      - name: Check Application Types
        run: cd client && pnpm type-check

      - name: Check Application Types
        run: cd client && pnpm prettier:fix
